config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :brands,only:[:index,:show]
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'card#pay'
    end
  end
  resources :items do
    get 'select_category' , to: 'items#select_category', on: :collection
    post 'resale', to: 'items#resale', on: :member
    post 'stop', to: 'items#stop', on: :member
    resources :comments, only: [:create, :update]
    resources :favorite_items, only: [:create, :destroy]
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    end
    resources :reviews, only: [:create, :new, :show]
  end
  resources :user_profiles, only: [:new, :create, :edit]
  resources :addresses, only: [:new, :create, :edit, :show, :update]
  resources :users, only: [:index, :show, :edit, :new, :update] do
    get :logout, on: :collection
  end
  resources :purchases, only: [:new]
  resources :categories, only:[:index,:show]
  root to: "items#index"
  get 'search', to: 'items#search'
  get 'purchased', to: 'purchases#purchased'
  get 'reviews', to: 'reviews#index'
  resources :exhibits, only: [:index] do
    get 'sold', to: 'exhibits#sold', on: :collection
  end
  get 'favorite_items', to: 'favorite_items#index'
end

app/models/favorite_item.rb
class FavoriteItem < ApplicationRecord
  belongs_to :item, counter_cache: :favorite_items_count
  belongs_to :user

  validates :user_id, presence: true
  validates :item_id, presence: true
  validates_uniqueness_of :item_id, scope: :user_id
end

app/controllers/favorite_items_controller.rb
class FavoriteItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:create, :destroy]

    def index
      @likes = current_user.favorite_items
    end

    def create
      @favorite_item = FavoriteItem.create(user_id: current_user.id, item_id: params[:item_id])
      @item.reload
    end

    def destroy
      @favorite_item = FavoriteItem.find_by(user_id: current_user.id, item_id: params[:item_id])
      @favorite_item.destroy
      @item.reload
    end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/views/favorite_items/_favorite_item.html.haml
- if user_signed_in?
  - unless item.favorite_item_user(current_user.id).blank?
    = link_to item_favorite_item_path(item_id: item.id,id: item.favorite_items[0].id), class:"favorite_item_link", method: :delete, remote: true do
      .itemDetail__button__left__like__no
        =fa_icon "heart",class:"icon-like"
        %span いいね！
        = item.favorite_items_count
  - else
    = link_to item_favorite_items_path(item.id),class:"favorite_item_link", method: :post, remote: true do
      .itemDetail__button__left__like__yes
        =fa_icon "heart",class:"icon-like"
        %span いいね！
        = item.favorite_items_count
- else 
  .itemDetail__button__left__like__yes
    =fa_icon "heart",class:"icon-like"
    %span いいね！
    = item.favorite_items_count

app/views/favorite_items/create.js.haml
$(".itemDetail__button__left__like__#{@item.id}").html("#{escape_javascript(render partial: 'favorite_items/favorite_item', locals: {item: @item, favorite_items: @favorite_items})}")

app/views/favorite_items/destroy.js.haml
$(".itemDetail__button__left__like__#{@item.id}").html("#{escape_javascript(render partial: 'favorite_items/favorite_item', locals: {item: @item, favorite_item: @favorite_item})}")

app/views/favorite_items/index.html.haml
-breadcrumb :exhibits
.user-main
  .user-container
    = render '/users/sidebar'
    .user-container_right-content
      .user-container_right-content_info
        .user-container_right-content_info_content
          .user-container_right-content_info_content
            .user-container_right-content_info_content_title
              %ul
                %li
                  いいね！一覧
            .user-container_right-content_info_content_list
              %ul
                - @likes.each do |like|
                  - unless like.item.exhibit.status == 3
                    %li
                      = link_to item_path(like.item.id) do
                        .user-container_right-content_info_content_list_icon
                          - if like.item.exhibit.status == 2
                            .itemDetail__main__photo__soldOut-mini
                          %img{alt: "メルカリ", height: "48px", width: "48px", src: "#{like.item.item_images[0].image}"}
                        .user-container_right-content_info_content_list_detail
                          = like.item.name
                          .user-container_right-content_info_content_list_detail_sellList
                            ¥
                            = like.item.price
                        .user-container_right-content_info_content_list_next
                          =fa_icon "angle-right"