config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :brands,only:[:index,:show]
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'card#pay'
    end
  end
  resources :items do
    get 'select_category' , to: 'items#select_category', on: :collection
    post 'resale', to: 'items#resale', on: :member
    post 'stop', to: 'items#stop', on: :member
    resources :comments, only: [:create, :update]
    resources :favorite_items, only: [:create, :destroy]
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    end
    resources :reviews, only: [:create, :new, :show]
  end
  resources :user_profiles, only: [:new, :create, :edit]
  resources :addresses, only: [:new, :create, :edit, :show, :update]
  resources :users, only: [:index, :show, :edit, :new, :update] do
    get :logout, on: :collection
  end
  resources :purchases, only: [:new]
  resources :categories, only:[:index,:show]
  root to: "items#index"
  get 'search', to: 'items#search'
  get 'purchased', to: 'purchases#purchased'
  get 'reviews', to: 'reviews#index'
  resources :exhibits, only: [:index] do
    get 'sold', to: 'exhibits#sold', on: :collection
  end
  get 'favorite_items', to: 'favorite_items#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  
  has_one :user_profile, dependent: :destroy
  accepts_nested_attributes_for :user_profile
  has_one :address, dependent: :destroy
  has_one :card, dependent: :destroy
  accepts_nested_attributes_for :address
  has_many :exhibits, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :reviews
  has_many :favorite_items, dependent: :destroy

  validates :nickname, presence: true

  protected

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        nickname:  auth.info.name,
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @user_profile = @user.build_user_profile
    @address = @user.build_address
    render layout: 'form-layout-registration'
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    render layout: 'form-layout'
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :logout]
  before_action :set_review, only: [:index, :show]
  def index
    @user = User.find(current_user.id)
    @sold_exhibits = @user.exhibits.where(status: 2)
    @reviews = []
    @sold_exhibits.each do |exhibit|
      @reviews.push(exhibit.item.review)
    end
    @review_count = @reviews.count
  end

  def show
    @user = User.find(params[:id])
    @sold_exhibits = @user.exhibits.where(status: 2)
    @reviews = []
    @sold_exhibits.each do |exhibit|
      @reviews.push(exhibit.item.review)
    end
    @review_count = @reviews.count
    @review_good_count = 0
    @review_normal_count = 0
    @review_bad_count = 0
    @reviews.each do |review|
      if review.status == 1
        @review_good_count = @review_good_count + 1
      elsif review.status == 2
        @review_normal_count = @review_normal_count + 1
      else
        @review_bad_count = @review_bad_count + 1
      end
    end
    @exhibits = @user.exhibits
  end

  def edit
  end

  def new
    render layout: 'form-layout'
  end

  def update
    begin
      if current_user.update(user_params)
        current_user.user_profile.update(user_profile_params)
        redirect_to controller: 'users', action: 'edit'
      else
        render :edit
      end
    rescue => e
      render :edit 
    end
  end

  def logout
  end

  private
  def set_review
    @sold_exhibits = current_user.exhibits.where(status: 2)
    @reviews = []
    @sold_exhibits.each do |exhibit|
      @reviews.push(exhibit.item.review)
    end
  end

  def user_params
    params.require(:user).permit(:nickname)
  end

  def user_profile_params
    params.require(:user).require(:user_profile).permit(:introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.haml
.user-container_left-content
  .user-container_left-content_info
    .user-container_left-content_info_list
      %ul
        = link_to users_path do
          %li
            マイページ
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            お知らせ
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            やることリスト
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to favorite_items_path do
          %li
            いいね！一覧
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to new_item_path do
          %li
            出品する
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to exhibits_path do
          %li
            出品した商品 - 出品中
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            出品した商品 - 取引中
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to sold_exhibits_path do
          %li
            出品した商品 - 売却済み
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            購入した商品 - 取引中
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to purchased_path do
          %li
            購入した商品 - 過去の取引
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            ニュース一覧
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to reviews_path do
          %li
            評価一覧
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            ガイド
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            お問い合わせ
            .user-container_left-content_info_list
              =fa_icon "angle-right"
    .user-container_left-content_info_head
      メルペイ
    .user-container_left-content_info_list
      %ul
        %a{ href: '#'}
          %li
            売上・振込申請
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            ポイント
            .user-container_left-content_info_list
              =fa_icon "angle-right"
    .user-container_left-content_info_head
      設定
    .user-container_left-content_info_list
      %ul
        = link_to edit_user_path(current_user) do
          %li
            プロフィール
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to edit_address_path(current_user) do
          %li
            発送元・お届け先住所変更
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        - if user_signed_in?
          = link_to card_path(current_user.id), data: {"turbolinks" => false} do
            %li
              支払い方法
              .user-container_left-content_info_list
                =fa_icon "angle-right"
        - else
          = link_to new_user_path do
            %li
              支払い方法
              .user-container_left-content_info_list
                =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            メール/パスワード
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        - if user_signed_in?
          = link_to address_path(current_user.id) do
            %li
              本人情報
              .user-container_left-content_info_list
                =fa_icon "angle-right"
        - else
          = link_to new_user_path do
            %li
              支払い方法
              .user-container_left-content_info_list
                =fa_icon "angle-right"
        %a{ href: '#'}
          %li
            電話番号の確認
            .user-container_left-content_info_list
              =fa_icon "angle-right"
        = link_to logout_users_path do
          %li
            ログアウト
            .user-container_left-content_info_list
              =fa_icon "angle-right"

app/views/users/edit.html.haml
-breadcrumb :user_edit
.userProfileEditMain
  .clearBoth
  .user-container
    .userProfileEdit
      = render 'sidebar'
      .userProfileEdit__main
        %section
          %h2.userProfileEdit__main__head プロフィール
          = form_with model: current_user do |f|
            %input{type: "hidden"}/
            .userProfileEdit__main__image
              %figure.userProfileEdit__main__image__user
                - if current_user.user_profile.avatar == nil
                  =image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png",alt: "usre", height: "60px", width: "60px")
                - else
                  =image_tag("#{current_user.user_profile.avatar}",alt: "usre", height: "60px", width: "60px")
                = f.text_field :nickname ,class: "userProfileEdit__main__image__user__nameBtn", placeholder: "例)AYA★セール中", id: "user_nickname"
                .userProfileEdit__main__image__user__nameBtnerror
                  %p#user_nickname.nickname
            .userProfileEdit__main__bottom
              = f.fields_for current_user.user_profile do |prf|
                = prf.text_area :introduction,class: "userProfileEdit__main__bottom__form__comment"
              = f.submit "変更する", class: "userProfileEdit__main__bottom__form__btn", name: "button"
      .clearBoth

app/views/users/index.html.haml
-breadcrumb :users 
.user-main
  .user-container
    = render 'sidebar'
    .user-container_right-content
      .user-container_right-content_info
        .user-container_right-content_info_head
          = link_to user_path(@user) do 
            .user-container_right-content_info_head_icon
              %img{alt: "メルカリ", height: "60px", width: "60px", src: "http://static.mercdn.net/images/mercari_profile.png", class: "user-container_right-content_info_head_icon_image"}
            .user-container_right-content_info_head_name
              = @user.nickname
            .user-container_right-content_info_head_review
              評価
              = @review_count
              出品数
              = @user.exhibits.count
            .user-container_right-content_info_head_info
        .user-container_right-content_info_content
          .user-container_right-content_info_content
            .user-container_right-content_info_content_title
              %ul
                %li{class: "active"}
                  お知らせ
                %li
                  やることリスト
            .user-container_right-content_info_content_list
              %ul
                %li
                  .user-container_right-content_info_content_list_icon
                    %img{alt: "メルカリ", height: "48px", width: "48px", src: "http://static.mercdn.net/images/mercari_profile.png"}
                  .user-container_right-content_info_content_list_detail
                    %a{ href: '#'}
                      テキストテキストテキストテキストテキストテキスト
                    .user-container_right-content_info_content_list_detail_time
                      %i.far.fa-clock
                      21時間前
                  .user-container_right-content_info_content_list_next
                    =fa_icon "angle-right"
                %li
                  .user-container_right-content_info_content_list_icon
                    %img{alt: "メルカリ", height: "48px", width: "48px", src: "http://static.mercdn.net/images/mercari_profile.png"}
                  .user-container_right-content_info_content_list_detail
                    %a{ href: '#'}
                      テキストテキストテキストテキストテキストテキスト
                    .user-container_right-content_info_content_list_detail_time
                      %i.far.fa-clock
                      21時間前
                  .user-container_right-content_info_content_list_next
                    =fa_icon "angle-right"
                %li
                  .user-container_right-content_info_content_list_icon
                    %img{alt: "メルカリ", height: "48px", width: "48px", src: "http://static.mercdn.net/images/mercari_profile.png"}
                  .user-container_right-content_info_content_list_detail
                    %a{ href: '#'}
                      テキストテキストテキストテキストテキストテキスト
                    .user-container_right-content_info_content_list_detail_time
                      %i.far.fa-clock
                      21時間前
                  .user-container_right-content_info_content_list_next
                    =fa_icon "angle-right"
                %li
                  .user-container_right-content_info_content_list_icon
                    %img{alt: "メルカリ", height: "48px", width: "48px", src: "http://static.mercdn.net/images/mercari_profile.png"}
                  .user-container_right-content_info_content_list_detail
                    %a{ href: '#'}
                      テキストテキストテキストテキストテキストテキスト
                    .user-container_right-content_info_content_list_detail_time
                      %i.far.fa-clock
                      21時間前
                  .user-container_right-content_info_content_list_next
                    =fa_icon "angle-right"
                %li
                  .user-container_right-content_info_content_list_icon
                    %img{alt: "メルカリ", height: "48px", width: "48px", src: "http://static.mercdn.net/images/mercari_profile.png"}
                  .user-container_right-content_info_content_list_detail
                    %a{ href: '#'}
                      テキストテキストテキストテキストテキストテキスト
                    .user-container_right-content_info_content_list_detail_time
                      %i.far.fa-clock
                      21時間前
                  .user-container_right-content_info_content_list_next
                    =fa_icon "angle-right"
                %li{class: "user-container_right-content_info_content_list_go"}
                  %a{ href: '#'}
                    一覧を見る
            -# .user-container_right-content_info_content_info
            -#   %a{ href: 'http://google.co.jp'}
            -#     一覧を見る
      .user-container_right-content_items
        .user-container_right-content_items_head
          購入した商品
        .user-container_right-content_items_title
          %ul
            %li{class: "active"}
              取引中
            %li
              過去の取引
        .user-container_right-content_items_list
          .user-container_right-content_items_list_none
            %img{alt: "メルカリ", height: "120px", width: "120px", src: "http://static.mercdn.net/images/mercari_profile.png", class: "user-container_right-content_items_list_none_image"}
            %br
            取引中の商品はありません。

app/views/users/logout.html.haml
- breadcrumb :logout
.user-main
  -# ここにパンくずきます
  .clearBoth
  .user-container
    .logoutWrapper
      = render 'sidebar'
      .logoutMain
        .logoutMain__container
          %form.logoutMain__container__inner(action="")
            .logoutMain__container__inner__logOutBtn
              = link_to destroy_user_session_path{:method }, method: :delete do
                %button.logoutMain__container__inner__logOutBtn__btn
                  ログアウト

app/views/users/new.html.haml
.user-form
  %main.user-form__main
    .user-form__main__warpper
      %h2.user-form__main__data 
        新規会員登録
      .user-form__main__box
        = link_to new_user_registration_path do
          .user-form__main__box__mail
            %i.fa.fa-envelope
            メールアドレスで登録
        = link_to user_facebook_omniauth_authorize_path do
          .user-form__main__box__facebook
            %i.fab.fa-facebook-square
            Facebookで登録
        = link_to user_google_oauth2_omniauth_authorize_path do
          .user-form__main__box__google
            %i.fab.fa-google
            Googleで登録

app/views/users/show.html.haml
.user-details
  .user-details_profile
    .user-details_profile_box
      .user-details_profile_box_icon
        %img{alt: "メルカリ", height: "180px", width: "180px", src: "http://static.mercdn.net/images/mercari_profile.png", class: "user-container_right-content_info_head_icon_image"}
      .user-details_profile_box_name
        = @user.nickname
      .user-details_profile_info
        %span.user-details_profile_info_list
          評価
          = @review_count
        %span.user-details_profile_info_list
          出品数
          = @user.exhibits.count
  .user-details_info
    .user-details_info_review
      %span.user-details_info_review_icon
        %i.fa.fa-laugh{class: "user-details_info_review_icon_size good-icon"}
        %span.user-details_info_review_icon_number
          = @review_good_count
      %span.user-details_info_review_icon
        %i.fa.fa-meh{class: "user-details_info_review_icon_size normal-icon"}
        %span.user-details_info_review_icon_number
          = @review_normal_count
      %span.user-details_info_review_icon
        %i.fa.fa-tired{class: "user-details_info_review_icon_size bad-icon"}
        %span.user-details_info_review_icon_number
          = @review_bad_count
    .user-details_info_description
      = @user.user_profile.introduction
  .user-details_description_social
    .user-details_description_social_box
      = link_to users_path do
        %i.fab.fa-facebook-square{class: "user-details_description_social-icon facebook-icon"}
      = link_to users_path do
        %i.fab.fa-twitter-square{class: "user-details_description_social-icon twitter-icon"}
      = link_to users_path do
        %i.fab.fa-line{class: "user-details_description_social-icon line-icon"}
  .user-details_items
    %h2.user-details_items_title この出品者の商品
    .user-details_items_content
      - @exhibits.each do |exhibit|
        .user-details_items_content_box
          = link_to item_path(exhibit.item.id) do
            - unless exhibit.status == 3
              %section
                - if exhibit.status == 1
                  %p
                    =image_tag("#{exhibit.item.item_images[0].image}", id: "photoMain",alt: "#{exhibit.item.name}", width: "200px", height: "240px")
                - else
                  %p
                    .itemDetail__main__photo__soldOut
                    =image_tag("#{exhibit.item.item_images[0].image}", id: "photoMain",alt: "#{exhibit.item.name}", width: "200px", height: "240px")
                %p
                  = exhibit.item.name
                %p
                  ¥
                  = exhibit.item.price
                  (税込)
                =fa_icon "heart",class:"icon-like"
                %span.like-num
                  = exhibit.item.favorite_items_count
                