config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :brands,only:[:index,:show]
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'card#pay'
    end
  end
  resources :items do
    get 'select_category' , to: 'items#select_category', on: :collection
    post 'resale', to: 'items#resale', on: :member
    post 'stop', to: 'items#stop', on: :member
    resources :comments, only: [:create, :update]
    resources :favorite_items, only: [:create, :destroy]
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    end
    resources :reviews, only: [:create, :new, :show]
  end
  resources :user_profiles, only: [:new, :create, :edit]
  resources :addresses, only: [:new, :create, :edit, :show, :update]
  resources :users, only: [:index, :show, :edit, :new, :update] do
    get :logout, on: :collection
  end
  resources :purchases, only: [:new]
  resources :categories, only:[:index,:show]
  root to: "items#index"
  get 'search', to: 'items#search'
  get 'purchased', to: 'purchases#purchased'
  get 'reviews', to: 'reviews#index'
  resources :exhibits, only: [:index] do
    get 'sold', to: 'exhibits#sold', on: :collection
  end
  get 'favorite_items', to: 'favorite_items#index'
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:index, :pay]

  def index
    if current_user.card.present?
      card = current_user.card
      Payjp.api_key = ENV["ENV['PAYJP_KEY']"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
    render layout: 'form-layout'
  end

  def purchased
    @purchases = current_user.purchases
  end

  def pay
    price = @item.price
    card = current_user.card
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    amount: price,
    customer: card.customer_id,
    currency: 'jpy',
    )
    @item.exhibit.status = 2
    @item.exhibit.save
    Purchase.create(item_id: @item.id, user_id: current_user.id)
    redirect_to new_item_review_path(@item)
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/index.html.haml
.itemBuy
  %main.itemBuy__main
    %section.itemBuy__main__container
      %h2.itemBuy__main__container__head
        購入内容の確認
      %section.itemBuy__main__container__wrapper
        .itemBuy__main__container__wrapper__inner
          %h3.itemBuy__main__container__wrapper__inner__itemImage
            = image_tag("#{@item.item_images[0].image}", id: "photoMain", "data-url": "#{@item.item_images[0].image}" ,alt: "#{@item.name}", height: "128px", width: "128px")
          %p.itemBuy__main__container__wrapper__inner__itemName
            = @item.name
          .itemBuy__main__container__wrapper__inner__formBuy
            %p.itemBuy__main__container__wrapper__inner__formBuy__price
              = converting_to_jpy(@item.price)
              %span.itemBuy__main__container__wrapper__inner__formBuy__price__tax
                送料込み
            %ul.itemBuy__main__container__wrapper__inner__formBuy__point
              %li.itemBuy__main__container__wrapper__inner__formBuy__point__pointBtn
                .itemBuy__main__container__wrapper__inner__formBuy__point__pointBtn__text
                  ポイントはありません
            %ul.itemBuy__main__container__wrapper__inner__formBuy__pay
              %li.itemBuy__main__container__wrapper__inner__formBuy__pay__inner
                .itemBuy__main__container__wrapper__inner__formBuy__pay__inner__text
                  支払い金額
                .itemBuy__main__container__wrapper__inner__formBuy__pay__inner__price
                  %span
                    = converting_to_jpy(@item.price)
            = form_tag(pay_item_purchases_path, method: :post) do
              = hidden_field_tag :id, @item.id
              =button_tag class:"itemBuy__main__container__wrapper__inner__formBuy__buyBtn" do
                購入する
      %section.itemBuy__main__container__userInfo
        .itemBuy__main__container__userInfo__inner
          %h3 配送先
          %address.itemBuy__main__container__userInfo__inner__text
            %p
              = current_user.address.postal_code
            %p
              = current_user.address.prefecture
              = current_user.address.city
              = current_user.address.town_number
              = current_user.address.building
            %p
              = current_user.address.last_name
              = current_user.address.first_name
          .itemBuy__main__container__userInfo__inner__text
          =link_to edit_address_path(current_user.id) do
            変更する
            %i=fa_icon "chevron-right",class:"itemDetail__icon-arrow-right"
      %section.itemBuy__main__container__userInfo
        - if @default_card_information.nil?
          .itemBuy__main__container__userInfo__inner
            %h3 支払い方法
            .itemBuy__main__container__userInfo__inner__text
            %p
            = link_to card_path(current_user.id), data: {"turbolinks" => false} do
              変更する
              %i=fa_icon "chevron-right",class:"itemDetail__icon-arrow-right"
        - else
          .itemBuy__main__container__userInfo__inner
            %h3 支払い方法
            .itemBuy__main__container__userInfo__inner__text
              %p
                = "**** **** **** " + @default_card_information.last4
              %p
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
            %figure
              =image_tag("master_card_001.png",width:"30px")
            %p
            = link_to card_path(current_user.id) do
              変更する
              %i=fa_icon "chevron-right",class:"itemDetail__icon-arrow-right"

app/views/purchases/purchased.html.haml
-breadcrumb :purchased
.user-main
  .user-container
    = render '/users/sidebar'
    .user-container_right-content
      .user-container_right-content_info
        .user-container_right-content_info_content
          .user-container_right-content_info_content
            .user-container_right-content_info_content_title
              %ul
                %li
                  取引中
                %li{class: "active"}
                  過去の取引
            .user-container_right-content_info_content_list
              %ul
                - @purchases.each do |purchase|
                  %li
                    = link_to item_path(purchase.item.id) do
                      .user-container_right-content_info_content_list_icon
                        %img{alt: "メルカリ", height: "48px", width: "48px", src: "#{purchase.item.item_images[0].image}"}
                      .user-container_right-content_info_content_list_detail
                        =purchase.item.name
                        を購入しました。取引が完了しました。
                        .user-container_right-content_info_content_list_detail_sellList
                          .user-container_right-content_info_content_list_detail_sold
                            取引完了
                      .user-container_right-content_info_content_list_next
                        =fa_icon "angle-right"
                - if @purchases.empty?
                  .user-container_right-content_items_list
                    .user-container_right-content_items_list_none
                      %img{alt: "メルカリ", height: "120px", width: "120px", src: "http://static.mercdn.net/images/mercari_profile.png", class: "user-container_right-content_items_list_none_image"}
                      %br
                      過去の取引はありません。