config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :brands,only:[:index,:show]
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'card#pay'
    end
  end
  resources :items do
    get 'select_category' , to: 'items#select_category', on: :collection
    post 'resale', to: 'items#resale', on: :member
    post 'stop', to: 'items#stop', on: :member
    resources :comments, only: [:create, :update]
    resources :favorite_items, only: [:create, :destroy]
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    end
    resources :reviews, only: [:create, :new, :show]
  end
  resources :user_profiles, only: [:new, :create, :edit]
  resources :addresses, only: [:new, :create, :edit, :show, :update]
  resources :users, only: [:index, :show, :edit, :new, :update] do
    get :logout, on: :collection
  end
  resources :purchases, only: [:new]
  resources :categories, only:[:index,:show]
  root to: "items#index"
  get 'search', to: 'items#search'
  get 'purchased', to: 'purchases#purchased'
  get 'reviews', to: 'reviews#index'
  resources :exhibits, only: [:index] do
    get 'sold', to: 'exhibits#sold', on: :collection
  end
  get 'favorite_items', to: 'favorite_items#index'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  include JpPrefecture
  # jp_prefecture :origin_of_delivery
  has_many :item_images, dependent: :delete_all
  accepts_nested_attributes_for :item_images
  has_many :categories, through: :item_categories
  belongs_to :category,optional: true
  belongs_to :brand,optional: true
  has_one :exhibit, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :purchases
  belongs_to  :size
  has_one :review
  has_many :favorite_items, dependent: :destroy

  with_options presence: true do
    validates :name, :description, :category_id, :size_id, :status, :shipping_fee, :how_to_shipping, :prefecture_id, :day, :price
  end
  validates :price, numericality: {greater_than_or_equal_to: 300,less_than_or_equal_to: 9_999_999}

  scope :latest_four_items, -> {order("created_at DESC").limit(4)}

  def favorite_item_user(user_id) #いいねしているかどうか
    favorite_items.find_by(user_id: user_id)
  end

  enum status: {"新品、未使用": 1, "未使用に近い": 2, "目立った傷や汚れなし": 3, "やや傷や汚れあり": 4, "傷や汚れあり": 5, "全体的に状態が悪い": 6}
  enum day: {"1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3}
  enum shipping_fee: {"送料込み(出品者負担)": 1,"着払い(購入者負担)": 2 }
  enum exhibitor_burden:{ "未定":1,"らくらくメルカリ便":2,"ゆうメール":3,"レターパック":4,"普通郵便(定型,定形外)":5, "クロネコヤマト":6,"ゆうパック":7,"クリックポスト":8,"ゆうパケット":9}
  enum purchaser_burden:{ "未定　":1,"クロネコヤマト　":2,"ゆうパック　":3,"ゆうメール　":4}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
     
  before_action :authenticate_user!, only: [:new, :create, :resale, :stop, :destroy]
  before_action :set_parents, only: [:new, :edit]
  before_action :set_item, only: [:show, :edit, :update, :resale, :stop, :destroy]
  before_action :set_image, only: [:edit, :update]

  def index
    $query = Item.ransack(params[:q])
    @ladies =Item.where(category_id: Category.first.subtree_ids).latest_four_items
    @mens =  Item.where(category_id: Category.second.subtree_ids).latest_four_items
    @baby =  Item.where(category_id: Category.third.subtree_ids).latest_four_items
    @interior =  Item.where(category_id: Category.fourth.subtree_ids).latest_four_items
    @chanel =Brand.first.items.latest_four_items
    @vuitton =Brand.second.items.latest_four_items
    @supreme =Brand.third.items.latest_four_items
    @nike=Brand.fourth.items.latest_four_items
  end

  def new
    render layout: 'form-layout'
    @item = Item.new
    @image = @item.item_images.build
  end

  def create
    if params[:brands][:name].present?
      brand = Brand.find_by(name: params[:brands][:name])
      brand_id = brand.present? ? brand.id : Brand.create(name: params[:brands][:name]).id
    end
    @item = Item.new(item_params)
    @item[:brand_id] = brand_id
    if @item.save
      params[:images][:image].reverse.each do |i|
        @image = @item.item_images.create(image: i.tempfile, item_id: @item.id)
      end
      Exhibit.create(item_id: @item.id, user_id: current_user.id)
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    render layout: 'form-layout'
  end

  def update
    brand_id　= nil
    if params[:item][:brands][:name].present?
      brand = Brand.find_by(name: params[:item][:brands][:name])
      brand_id = brand.present? ? brand.id : Brand.create(name: params[:item][:brands][:name]).id
    end
    @item[:brand_id] = brand_id
    if @item.update(item_parameter)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def show
    @brand = @item.brand
    @category =@item.category
    @comment = Comment.new
    @comments = @item.comments
    @user = @item.exhibit.user
    @sold_exhibits = @user.exhibits.where(status: 2)
    @reviews = []
    @sold_exhibits.each do |exhibit|
      @reviews.push(exhibit.item.review)
    end
    @review_good_count = 0
    @review_normal_count = 0
    @review_bad_count = 0
    @reviews.each do |review|
      if review.status == 1
        @review_good_count = @review_good_count + 1
      elsif review.status == 2
        @review_normal_count = @review_normal_count + 1
      else
        @review_bad_count = @review_bad_count + 1
      end
    end
  end

  def resale
    @item.exhibit.status = 1
    @item.exhibit.save
    redirect_to action: 'show', id: @item.id
  end

  def stop
    @item.exhibit.status = 3
    @item.exhibit.save
    redirect_to action: 'show', id: @item.id
  end

  def search
    @parents = Category.where(id: 1..13)
    @children = @parents.where(id: params[:id])
    $query = Item.ransack(params[:q])
    @items = $query.result.includes(:category, :brand)
    @new_items =Item.all.order(created_at: "DESC")
  end

  def destroy
    @item.destroy
    redirect_to controller: 'exhibits', action: 'index'
  end

  def select_category
    @category = Category.find(params[:parent_id])
    puts params[:parent_id]
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_image
    @images = @item.item_images
  end

  def item_params
    params.permit(:name, :description, :category_id, :size_id, :status, :shipping_fee, :how_to_shipping, :prefecture_id, :day, :price, images_attributes: [:image])
  end

  def item_parameter
    params.require(:item).permit(:name, :description, :category_id, :size_id, :status, :shipping_fee, :how_to_shipping, :prefecture_id, :day, :price)
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def search_params
    params.require(:q).permit(:name_cont)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def date_format(datetime)
    time_ago_in_words(datetime) + '前'
  end
end

app/views/items/_category-menue.html.haml
- Category.roots.order("id ASC").each do |parent|
  %li#nav-drawer__ctd2
    =link_to "#{parent.name}",category_path(parent.id),class: "parent-l"
    %ul#nav-drawer__2
      -parent.children.limit(14).each do |chaild|
        %li#nav-drawer__ctd3
          =link_to "#{chaild.name}",category_path(chaild.id),class: "chaild-l"
          %ul#nav-drawer__3
            -chaild.children.limit(14).each do |grandchaild|
              %li#nav-drawer__ctd4
                =link_to "#{ grandchaild.name}",category_path(grandchaild.id),class:"grandchaild-l" 
%li.all
  =link_to "カテゴリー一覧",categories_path
  

app/views/items/_footer.html.haml
.app-banner
  =image_tag("banner_bottom_tmp.jpg",class: "bottom-image")
  
%footer
  %nav.nav-contents
    .footer-cell
      %h2 メルカリについて
      %ul
        %li  
        %li　採用情報
        %li　プレスリリース
        %li　公式ブログ
        %li　メルカリロゴ利用ガイドライン
        %li.footer-social-link
          =link_to "/" do
            =fa_icon "twitter"
        %li.footer-social-link
          =link_to "/" do
            =fa_icon "facebook-square"
    .footer-cell
      %h2 ヘルプガイド
      %ul
        %li　メルカリガイド
        %li　らくらくメルカリ便
        %li　ゆうゆうメルカリ便
        %li　大型メルカリ便
        %li　車体取引ガイド
        %li　メルカリ安心・あんぜん宣言！
        %li　偽ブランド品撲滅への取り組み
        %li　メルカリボックス
    .footer-cell--full-width
      %h2 ヘルプガイド
      .inner-footer-cell-wrapper
        .inner-footer-cell
          %ul
            %li　メルカリガイド
            %li　らくらくメルカリ便
            %li　ゆうゆうメルカリ便
            %li　大型メルカリ便
        .inner-footer-cell
          %ul
            %li　メルカリガイド
            %li　らくらくメルカリ便
            %li　ゆうゆうメルカリ便
            %li　大型メルカリ便
  .footer_bottom
    =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?3160895340"),"/",class: "icon-l"
    .footer-copyright
      %span.copyright © 2019 Mercari
.footer-sell-btn
  =link_to "/items/new" do
    %p.sell 出品
    =fa_icon"camera", class: 'icon'

app/views/items/_header.html.haml
.container
  .header1
    .header-inner
      .header-inner__top
        %h1
          =link_to image_tag("mercari_logo_horizontal.png",:size=> "160x50",class: "img"),"/"
        = search_form_for($query,url: search_path ,class: "header-inner__top__search") do |f|
          = f.search_field :name_cont_any,class: "header-inner__top__search__form", placeholder: "キーワードから探す"
          = f.submit 'Search',class: "header-inner__top__search__button"
          = button_tag type:"submit", class: "header-inner__top__search__button" do 
            = fa_icon "search"
      .header-inner__bottom
        .header-inner__bottom__nav1
          %ul.nav1
            %li.ctd
              = link_to categories_path  do
                =fa_icon "bars"
                %span カテゴリー
              %ul#nav-drawer
                = render "items/category-menue"
            %li.bl
              =link_to brands_path do
                =fa_icon "tag"
                %span ブランドから探す
              %ul.nav-drawer2
                - Brand.all.limit(4).each do |brand|
                  %li.bl2
                    =link_to "#{brand.name}",brand_path(brand.id)
                %li.all-brand
                  =link_to"ブランド一覧",brands_path
        -if user_signed_in?
          .header-inner__bottom__nav2
            %ul.nav2
              %li.Notice
                =fa_icon "bell"
                %span お知らせ
              %li.check
                =fa_icon "check"
                %span やることリスト
              %li.mypage
                =link_to users_path  do
                  =image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png")
                  %span マイページ
        -else
          .header-inner__bottom__nav2
            %ul.nav2-login
              %li.nav2-login__btn
                =link_to "新規会員登録", new_user_path,class: "signup"
              %li.nav2-login__btn 
                = link_to "ログイン", user_session_path,class: "login"
            
          

app/views/items/_left-comment-owner.html.haml
%li.itemComment__content__item__cl.clearfix
  .itemComment__content__item__cl__user
    = link_to user_path(comment.user) do
      %div
        =image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png",alt: "usre", height: "40px", width: "40px")
      .itemComment__content__item__cl__userName
        = comment.user.nickname
      - if comment.user.id == @item.exhibit.user.id
        .itemComment__content__item__cl__seller
          %p 出品者
  .itemComment__content__item__cl__body
    .itemComment__content__item__cl__body__text
      = comment.content
    .itemComment__content__item__cl__body__icon.clearfix
      %time.itemComment__content__item__cl__body__icon__left
        %i.itemComment-icon-time
          %i.far.fa-clock
        %span
          = date_format(comment.created_at)
      - if current_user.id == @item.exhibit.user.id
        .itemCommentMe__content__item__cl__body__icon__right__delete
          = link_to item_comment_path(comment.item.id, comment.id) , method: :patch, data: { confirm: 'コメントを削除しますか?' } do 
            %i=fa_icon "trash",class:"itemComment__icon__delete"
      .itemCommentMe__content__item__cl__body__icon__right__flag
        %form{action: "", method: ""}
          = button_tag type: "submit" do
            %i=fa_icon "flag",class:"itemComment__icon__flag"

app/views/items/_left-comment.html.haml
%li.itemComment__content__item__cl.clearfix
  .itemComment__content__item__cl__user
    = link_to user_path(comment.user) do
      %div
        =image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png",alt: "usre", height: "40px", width: "40px")
      .itemComment__content__item__cl__userName
        = comment.user.nickname
      - if comment.user.id == @item.exhibit.user.id
        .itemComment__content__item__cl__seller
          %p 出品者
  .itemComment__content__item__cl__body
    .itemComment__content__item__cl__body__text
      = comment.content
    .itemComment__content__item__cl__body__icon.clearfix
      %time.itemComment__content__item__cl__body__icon__left
        %i.itemComment-icon-time
          %i.far.fa-clock
        %span
          = date_format(comment.created_at)
      -# - if current_user.id == @item.exhibit.user.id
      -#   .itemCommentMe__content__item__cl__body__icon__right__delete
      -#     = link_to item_comment_path(comment.item.id, comment.id) , method: :patch, data: { confirm: 'コメントを削除しますか?' } do 
      -#       %i=fa_icon "trash",class:"itemComment__icon__delete"
      -# .itemCommentMe__content__item__cl__body__icon__right__flag
      -#   %form{action: "", method: ""}
      -#     = button_tag type: "submit" do
      -#       %i=fa_icon "flag",class:"itemComment__icon__flag"

app/views/items/search.html.haml
-if @items == Item.all
  %p.breadcrumbs
    =link_to "メルカリ",root_path
-else
  -breadcrumb :search
.search-container
  .search-container__left
    .search-container__left__wrapper
      .search-container__left__wrapper__sort
        %select
          %option
            =sort_link($query, "価格順",:price,hide_indicator: true)
          %option
            =sort_link($query,"新着順", :created_at,hide_indicator: true)
        .search-container__left__wrapper__forms
          .search-container__left__wrapper__forms__label 詳細検索
          .search-container__left__wrapper__forms__form
            -if @items == Item.all
              = search_form_for($query,url: search_path) do |f|
                .search-container__left__wrapper__forms__form__label
                  =f.label :name,"キーワードを追加する"
                .search-container__left__wrapper__forms__form__keyword
                  =f.text_field :name, class: "input-keyword", value: nil
                #category_parent.search-container__left__wrapper__forms__form__select-parent
                  =f.collection_select :category_id,@parents,:id, :name, {include_blank: "---" },{id:'select_parent', class:"input-parents", required:"required"}
                #category_children.search-container__left__wrapper__forms__form__select-children
                  = f.collection_select :category_id, @children,:id, :name, {include_blank: "---" },{id:'select_children', class:"sell-form__main__detail__select-box__text", required:"required"}
                #category_grandchildren.search-container__left__wrapper__forms__form__select-grand-chaild
                  = f.collection_select :category_id, @parents[0].children[0].children,:id, :name, {include_blank: "---" },{id:'select_grondchildren', class:"sell-form__main__detail__select-box__text", required:"required"}
            -else
              = search_form_for($query,url: search_path) do |f|
                .search-container__left__wrapper__forms__form__label
                  =f.label :name,"キーワードを追加する"
                .search-container__left__wrapper__forms__form__keyword
                  =f.text_field :name, class: "input-keyword", value: "#{$query.conditions.first.values.first.value}"
                #category_parent.search-container__left__wrapper__forms__form__select-parent
                  =f.collection_select :category_id,@parents,:id, :name, {include_blank: "---" },{id:'select_parent', class:"input-parents", required:"required"}
                #category_children.search-container__left__wrapper__forms__form__select-children
                  = f.collection_select :category_id, @children,:id, :name, {include_blank: "---" },{id:'select_children', class:"sell-form__main__detail__select-box__text", required:"required"}
                #category_grandchildren.search-container__left__wrapper__forms__form__select-grand-chaild
                  = f.collection_select :category_id, @parents[0].children[0].children,:id, :name, {include_blank: "---" },{id:'select_grondchildren', class:"sell-form__main__detail__select-box__text", required:"required"}
  
  .search-container__right
    .search-container__right__wrapper
      -if @items != Item.all
        .search-container__right__wrapper__head
          #{$query.conditions.first.values.first.value}
          %span.result-head 
            の結果
            -if @items== []
              %p 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
      -else
        .search-container__right__wrapper__head
          新着アイテム
      .search-container__right__wrapper__number
        -# ="#{@items.length}"
      .search-container__right__wrapper__container
        -if @items ==[]
          %p新着アイテム
          -@new_items.each do |item|
            -if item.exhibit.status === 3
              %p
            -else
              .search-container__right__wrapper__container__box
                = link_to "",item_path(item.id) 
                .search-container__right__wrapper__container__box__image
                  - if item.exhibit.status === 2
                    .itemDetail__main__photo__soldOut
                  - elsif  item.exhibit.status === 3
                    .itemDetail__main__photo__soldStop
                  - else
                  =image_tag(item.item_images[0].image.to_s,class: "images")
                .search-container__right__wrapper__container__box__text
                  .search-container__right__wrapper__container__box__text__title #{item.name}
                  .search-container__right__wrapper__container__box__text__num


                    %span.like-num
                      = item.favorite_items_count
                    =fa_icon "heart",class:"icon-like"
                    .search-container__right__wrapper__container__box__text__num__price ¥#{item.price}
                  .search-container__right__wrapper__container__box__text__title__tax (税込)

        
        -else
          -@items.each do |item|
            -if item.exhibit.status === 3
              %p
            -else
              .search-container__right__wrapper__container__box
                = link_to "",item_path(item.id) 
                .search-container__right__wrapper__container__box__image
                  - if item.exhibit.status === 2
                    .itemDetail__main__photo__soldOut
                  - elsif  item.exhibit.status === 3
                    .itemDetail__main__photo__soldStop
                  - else

                  =image_tag(item.item_images[0].image.to_s,class: "images")
                .search-container__right__wrapper__container__box__text
                  .search-container__right__wrapper__container__box__text__title #{item.name}
                  .search-container__right__wrapper__container__box__text__num

                    %span.like-num
                      = item.favorite_items_count
                    =fa_icon "heart",class:"icon-like"
                    .search-container__right__wrapper__container__box__text__num__price ¥#{item.price}
                  .search-container__right__wrapper__container__box__text__title__tax (税込)
          

app/views/items/show.html.haml
- breadcrumb :item,@item
.itemDetail__space
.itemDetail
  %h1.itemDetail__title
    = @item.name
  .itemDetail__main
    .itemDetail__main__photo
      .itemDetail__main__photo__top{style: "width: 300px;"}
        - if @item.exhibit.status === 2
          .itemDetail__main__photo__soldOut
        - elsif  @item.exhibit.status === 3
          .itemDetail__main__photo__soldStop
        - else
        =image_tag("#{@item.item_images[0].image}", id: "photoMain", "data-url": "#{@item.item_images[0].image}" ,alt: "bag1")
      .itemDetail__main__photo__bottomBox
        - @item.item_images.each do |image|
          .itemDetail__main__photo__bottomBox__bottom
            =image_tag("#{image.image}", class: "photosub", id: "photoSub","data-url": "#{image.image}",alt: "#{@item.name}")
    %div
      %table.itemDetail__main__table
        %tbody
          %tr
            %th 出品者
            %td
              
              = link_to"#{@item.exhibit.user.nickname}",user_path(@item.exhibit.user.id)
              %div
                .itemDetail__main__tablel__itemUserRatings
                  =image_tag("icon-good.png",size: "16x16")
                  %span
                    = @review_good_count
                .itemDetail__main__tablel__itemUserRatings
                  =image_tag("icon-normal.png",size: "16x16")
                  %span
                    = @review_normal_count
                .itemDetail__main__tablel__itemUserRatings
                  =image_tag("icon-bad.png",size: "16x16")
                  %span
                    = @review_bad_count
            %tr
              / 一枠
              %th カテゴリー
              %td
                = link_to category_path(@category.parent.parent.id) do
                  #{@category.parent.parent.name}
                  %div
                = link_to category_path(@category.parent.id)  do
                  %i=fa_icon "chevron-right",class:"itemDetail__icon-arrow-right"
                  #{@category.parent.name}
                  %div
                = link_to category_path(@category.id)  do
                  %i=fa_icon "chevron-right",class:"itemDetail__icon-arrow-right"
                  #{@category.name}
            %tr
              / 一枠
              %th ブランド
              -if @brand == nil
                %td
              -else
                %td
                  = link_to "#{@brand.name}", brand_path(@brand.id)
            %tr
              / 一枠
              %th 商品の状態
              %td
                = @item.status
            %tr
              / 一枠
              %th 配送料の負担
              %td
                = @item.shipping_fee
            %tr
              / 一枠
              %th 配送の方法
              %td
                = @item.how_to_shipping
            %tr
              / 一枠
              %th 配送元地域
              %td
                =  @item.prefecture.name
                -# = link_to '東京都', 'show'
            %tr
              / 一枠
              %th 配送日の目安
              %td
                = @item.day
    .clearBoth
    .itemDetail__price
      %span.itemDetail__price__itemPrice
        = converting_to_jpy(@item.price)
        -# = @item.price
        -#  ¥ 3,380
      %span.itemDetail__price__tax (税込)
      %span.itemDetail__price__shippingFee
        -# 送料込み
        -if @item.shipping_fee == "送料込み(出品者負担)"
          送料込み
        -else
          着払い
    - if @item.exhibit.status == 2
      .itemDetail__buyBtn__sold 売り切れました
    - elsif @item.exhibit.status == 3
      - if user_signed_in? && @item.exhibit.user.id == current_user.id
        .itemDetail__editBtn__edit 商品の編集
        %p.itemDetail__or or
        = link_to resale_item_path, method: :post do
          .itemDetail__editBtn 出品を再開する
        = link_to item_path, method: :delete, data: { confirm: '本当に削除しますか？' } do
          .itemDetail__deleteBtn この商品を削除する
    - else
      - if user_signed_in? && @item.exhibit.user.id == current_user.id

        = link_to edit_item_path(@item.id) do
          .itemDetail__editBtn__edit 商品の編集
        #p.itemDetail__or or
        = link_to stop_item_path,class:"item_btn", method: :post do
          .itemDetail__editBtn 出品を一旦停止する
        = link_to item_path, class:"item_btn", method: :delete, data: { confirm: '本当に削除しますか？' } do
          .itemDetail__deleteBtn この商品を削除する
      - else
        =link_to "購入画面に進む" , item_purchases_path(@item) ,class: "itemDetail__buyBtn"
    .itemDetail__description
      %p.itemDetail__description__inner
        = @item.description
    .itemDetail__button.clearfix
      .itemDetail__button__left
        %div{class:"itemDetail__button__left__like__#{@item.id}"}
          = render partial: 'favorite_items/favorite_item', locals: {item: @item, favorite_items: @favorite_items}
        .itemDetail__button__left__report
          =fa_icon "flag",class:"itemDetail__icon__flag"
          不適切な商品の報告
      .itemDetail__button__right
        = link_to 'show' do
          =fa_icon "flag",class:"itemDetail__icon__clock"
          あんしん・あんぜんへの取り組み
  .itemComment__space
  .itemComment-itemPostBox
    .itemComment
      .itemComment__content
        %ul.itemComment__content__item
          - @comments.each do |comment|
            - if user_signed_in?
              -# ログイン時のコメント画面
              - if comment.user.id == current_user.id
                -# 自分のビュー
                %li.itemCommentMe__content__item__cl.clearfix
                  .itemCommentMe__content__item__cl__user
                    = link_to user_path(comment.user) do
                      %div
                        =image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png",alt: "usre", height: "40px", width: "40px")
                      .clearBoth
                      .itemCommentMe__content__item__cl__userName 
                        = comment.user.nickname
                      - if comment.user.id == @item.exhibit.user.id
                        .itemComment__content__item__cl__seller
                          %p 出品者
                  .itemCommentMe__content__item__cl__body
                    .itemCommentMe__content__item__cl__body__text
                      = comment.content
                    .itemCommentMe__content__item__cl__body__icon.clearfix
                      %time.itemCommentMe__content__item__cl__body__icon__left
                        %i.itemCommentMe-icon-time
                          %i.far.fa-clock
                        %span
                          = date_format(comment.created_at)
                      - if current_user.id == @item.exhibit.user.id
                        .itemCommentMe__content__item__cl__body__icon__right__delete
                          = link_to item_comment_path(comment.item.id, comment.id) , method: :patch, data: { confirm: 'コメントを削除しますか?' } do 
                            %i=fa_icon "trash",class:"itemComment__icon__delete"
                      .itemCommentMe__content__item__cl__body__icon__right__flag
                        %form{action: "", method: ""}
                          = button_tag type: "submit" do
                            %i=fa_icon "flag",class:"itemComment__icon__flag"
              - else
                -# 他の人のコメント
                = render partial: 'left-comment-owner', locals: { comment: comment }
            - else
              -# ログインしていない時のコメント画面
              = render partial: 'left-comment', locals: { comment: comment }
        .clearBoth
    .itemPostComment
      = form_for [@item, @comment],  html: { class: 'itemPostComment__form' } do |f|
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = f.text_field :content, class: 'itemPostComment__form__text'
        - if @item.exhibit.status === 2
          %span.itemPostComment__form__btn 売り切れのためコメントできません
        - elsif @item.exhibit.status === 3
          %span.itemPostComment__form__btn 公開停止中のためコメントできません
        - else
          =button_tag type: "submit" , class: "itemPostComment__form__btn" do
            %span コメントする
.itemDetail__space